variables:
  IMAGE_NAME: "sample-node"

stages:
  - release
  - ending

.only-version-change:
  refs:
    - main
  changes:
    - sample-node/.VERSION

release:
  image: docker:latest
  services:
    - docker:dind
  stage: release
  script:
    - export IMAGEVERSION=$(cat sample-node/.VERSION)
    - cd sample-node
    - docker build -t $CI_REGISTRY_IMAGE/$IMAGE_NAME -t $CI_REGISTRY_IMAGE/$IMAGE_NAME:$IMAGEVERSION .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/$IMAGE_NAME --all-tags
  only: !reference [.only-version-change]

ending:
  stage: ending
  script:
    - echo "end job"
